### ISSUE TITLE
Create games page

### ISSUE THREAD

**Issue by midorimici** [midorimici/fairy-chess-online#6]
`/games`
Fetch game data and display game informations.

from GraphCMS (static data)

```yml
name: string
description: string
boardSize: int
withCastling: bool
promotionCandidates: string list  # piece ids
initialBoardImage: one file media
isAsymmetric: bool
initialPiecePositions: JSON object
  [rank]:
    - pieceName | null
```

```
pieceName  ::= pieceColor pieceId | pieceId  # pieceColor must be omitted when it is symmetric game
pieceColor ::= 'W' | 'B'
pieceId    ::= [A-Z][a-zA-Z0-9]*
```

from Realtime Database (dynamic data), in later PR
- Whether there is a player waiting for another player in a public room: *boolean*

**Comment by midorimici** [comment]
Add piece model and contents to GraphCMS.

`piece`
`expandMoves` is useful to omit duplicated moves.

```yml
abbr: enum (piece id)
value: float
moves: JSON object (list of moveNode)
expandMoves?: enum['V' | 'H' | 'X']  # Add reversed moves of "moves" V: ↕, H: ↔, X: ↕↔ ↖↘ ↙↗
```

`moveNode`
tree structure

```yml
move: move
children?: moveNode[]
when?: string
```

`move`
Either the `ref` field, or `type` and `direction` fields are required.
Fields for hopper and penetration will not be implemented at this stage.

```yml
ref?: pieceId                    # Id of a piece to copy.
type?: enum['leaper' | 'rider']  # Required when ref is not specified.
direction?: [int, int]           # The direction seen from a white player. Top-right will be greater. Required when ref is not specified.
length?: number (0 -)            # The distance to run (for riders and hoppers). 0 or unspecified means infinity.
# Fields for hopper
# reach?: number
# captureHurdle?: boolean
# Fields for penetration
# penetrationLimit?: number (0 -) # The number of pieces that the piece penetrates. 0 means infinity.
reflectionLimit?: number (1 - 3)  # The times that the piece reflects on the edge of the board.
option?: enum['move-only' | 'capture-only']
```
